apiVersion: v1
kind: Service
metadata:
  name: {{ include "remember.fullname" . }}
  labels:
    {{- include "remember.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.webui.enabled }}
    - port: {{ .Values.webui.port }}
      targetPort: webui
      protocol: TCP
      name: webui
    {{- end }}
  selector:
    {{- include "remember.selectorLabels" . | nindent 4 }}
